### ISSUE TITLE
Pura API valid device types has changed - tabletop invalid now

### ISSUE THREAD

**Issue by RobertD502** [natekspencer/pypura#34]
Looks like `tabletop` isn't a valid device type allowed to be sent when getting devices from the API.

```
This error originated from a custom integration.

Logger: custom_components.pura.coordinator
Source: custom_components/pura/coordinator.py:50
Integration: Pura (documentation, issues)
First occurred: 1:09:59 PM (1 occurrences)
Last logged: 1:09:59 PM

Unknown exception while updating Pura data: 400 Client Error: Bad Request for url: https://trypura.io/mobile/api/users/devices?types=wall%2Ccar%2Ctabletop
Traceback (most recent call last):
  File "/config/custom_components/pura/coordinator.py", line 50, in _async_update_data
    if devices := await self.hass.async_add_executor_job(self.api.get_devices):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pypura/pura.py", line 97, in get_devices
    return self.__get("users/devices", params={"types": "wall,car,tabletop"})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pypura/pura.py", line 199, in __get
    return self.__request("get", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pypura/pura.py", line 194, in __request
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://trypura.io/mobile/api/users/devices?types=wall%2Ccar%2Ctabletop
```

Response from the Pura API indicating that the new device types allowed are `wall`, `car`, `plus`, `1`, `2`, `3`:
```
Logger: pypura.pura
Source: /usr/local/lib/python3.11/site-packages/pypura/pura.py:193
First occurred: 1:09:59 PM (1 occurrences)
Last logged: 1:09:59 PM

Status: 400 - {'message': 'query.types must be car, wall, plus, or 1, 2, 3'}
```

**Comment by RobertD502** [comment]
Ah, beat me to it haha. Just forked and saw the get_devices function was changed.

**Comment by natekspencer** [comment]
Resolved in 0.1.11. Thanks for the issue!

**Comment by RobertD502** [comment]
Bumped the Home Assistant component pypura requirement to `0.1.11` and can confirm that it is back up and running. Thanks for the quick turnaround time!

**Comment by RobertD502** [comment]
@natekspencer I know this isn't the repo for the HA integration, but I wanted to add a slight suggestion without opening an issue on that repo since it isn't a real "issue"/ you don't have discussions enabled on that repo and we already have a line of communication here:

I noticed that you don't write the [current state to home assistant](https://github.com/natekspencer/hacs-pura/blob/8c7c3ef368f2f3423f2d41182649c820112906e6/custom_components/pura/number.py#L85-L105) after sending a command to pura's API. As a result, for example, if my current intensity is 5 and I bump it up to 8 with the slider number entity, during a page refresh it reverts back to 5 until the call to the pura API returns updated coordinator data.

One way around this is to manually write the new state to the coordinator object prior to `async_request_refresh()`. For example, with the scent intensity number entity you'd add the following prior to the `async_request_refresh()` function:

```python
self._intensity_data["intensity"] = value
self.async_write_ha_state()
# Wait until refreshing data as the Pura API may return the old intensity if polled immediately after sending a command
asyncio.sleep(1)
await self.coordinator.async_request_refresh()
```

**If not writing the state and switching from an intensity of 5 to 8, notice the number entity reverts back to 5 when the page is refreshed:**


https://github.com/natekspencer/pypura/assets/52541649/048810a7-d869-4234-b9d4-4fe8d32e424b



**When writing the state - notice the number entity remains at the value it was just set to when refreshing the page:**

https://github.com/natekspencer/pypura/assets/52541649/88b76c87-d577-4e2e-918c-f86b981869f7


Although the reverting of values is most commonly seen if the HA UI is refreshed (the UI uses the old value from the coordinator data during a page refresh), this can also happen if the Pura API is polled prior to the new value being reflected in the returned data.

1) `await asyncio.sleep(1)` circumvents the polling issue by not polling the API until a second after a command is sent in order to ensure the returned Pura API data is up-to-date.
2) Writing the command value to the coordinator prior to requesting a refresh of the data circumvents the issue seen if a user refreshes the HA UI after sending a command to Pura.

It would also be worthwhile doing this for the `select`, `switch`, and `light` entities since they also involve sending commands.
