### ISSUE TITLE
[Feature Request] Use pycognito's Cognito class check_token function prior to making calls to the API

### ISSUE THREAD

**Issue by RobertD502** [natekspencer/pypura#36]
I noticed that I am getting a lot of `Status: 401 - {'message': 'jwt expired'}` messages returned by the API. I see that you use the `Cognito` class' `check_token` function in your `get_user` function. However, this isn't done in the other functions meant to get the devices and controlling a device. Any chance you'd consider adding a token check to these functions so we can ensure that the token hasn't expired prior to trying to fetch devices or controlling a device?

I haven't dealt with the pycognito library myself, but I'm assuming an expiration is returned when a token is obtained - perhaps to decrease computational time, the expiration date could be stored and the `check_token` function only called if we are past the expiration with the current token (this would also allow for renewal within that function all in one go).

**Comment by natekspencer** [comment]
All requests utilize the `RequestsSrpAuth` class for authorization which automatically handles validating and refreshing the token.

**Comment by RobertD502** [comment]
Maybe I'm reading this wrong:

After the [initial authentication, `self._auth` isn't None.](https://github.com/natekspencer/pypura/blob/8f7c6553e3dc9ec38bf89128d8786e057348da09/pypura/pura.py#L65-L71) In this case, the current `self._auth` is returned - wouldn't just returning not end up invoking the `__call__` method resulting in the token not being checked/renewed?

**Comment by natekspencer** [comment]
`RequestsSrpAuth` is a subclass of `AuthBase` from the requests library which allows for the request to be modified before it is dispatched. The `__call__` method is then fired on every request, which for `RequestsSrpAuth`, verifies the tokens via the `check_token(renew=True)` method and updates as needed.

See https://requests.readthedocs.io/en/latest/user/advanced/?highlight=AuthBase#custom-authentication for more info.

**Comment by natekspencer** [comment]
> Maybe I'm reading this wrong:

You're not reading it wrong per se, but you are misunderstanding what happens behind the scenes. This is an object that only needs to be created once and then is referenced elsewhere.

**Comment by RobertD502** [comment]
Got it! Thanks for clarifying.
