### ISSUE TITLE
3 letter fragrance code

### ISSUE THREAD

**Issue by thenoid** [natekspencer/pypura#61]
homeassistant    | 2024-02-17 16:35:39.427 WARNING (MainThread) [pypura.utils] Unknown fragrance code 'PPO', please report this at https://github.com/natekspencer/pypura/issues/1
homeassistant    | 2024-02-17 16:35:39.429 WARNING (MainThread) [pypura.utils] Unknown fragrance code 'PTM', please report this at https://github.com/natekspencer/pypura/issues/1
homeassistant    | 2024-02-17 16:35:39.432 WARNING (MainThread) [pypura.utils] Unknown fragrance code 'BHA', please report this at https://github.com/natekspencer/pypura/issues/1

I'm not sure if this belongs here? or in https://github.com/natekspencer/hacs-pura  HA keeps showing the following errors.  Looking at the actual inserts, they all of a 4 letter code, but for some reason it's only showing a 3 letter code in the error?  

Note all these fragrances are in the `fragrances.json` but as `PPOH`, `PTMH` and `BHAH`.

**Comment by natekspencer** [comment]
It's possible Pura maps certain 4-letter codes to 3-letter codes on the backend where they represent the same fragrance. I'll add these 3-letter ones and do a new release. Thanks!

**Comment by natekspencer** [comment]
This has been released.
